config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to task_url(@task) and return
    else
      render :new
    end
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.attributes = task_params
    if @task.save
      redirect_to task_url(@task) and return
    else
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>
<%= form_with model: @task, url: task_path(@task), method: :patch, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit '更新' %>
<% end %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>
<table>
  <% @tasks.each do |task| %>
    <tr>
      <%= task.content %>
    </tr>
  <% end %>
</table>

app/views/tasks/new.html.erb
<h2>タスク登録</h2>
<%= form_with model: @task, url: tasks_path, method: :post, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit '登録' %>
<% end %>

app/views/tasks/show.html.erb
<h2>タスク詳細</h2>
<p>タスクの内容：<%= @task.content %></p>